### PR TITLE
Add useIntegers option

### PR DESCRIPTION
**Pull request by mbenedettini**
If you are doing things right, behind the curtains your system stores money as integers, NEVER EVER as decimals/float point, otherwise you'll suffer from [floating point rounding error](https://softwareengineering.stackexchange.com/questions/101163/what-causes-floating-point-rounding-errors).

This option allows an automagic conversion, so that in your model you can have, for example, `123456` and it will be displayed/masked as `$ 1234.56` (in case your prefix is `$` and precision is `2`). If user changes that amount to `$ 7890.12` you'll get `789012` in your model.

### CODE REVIEW

**Comment by guillep2k** [comment]
But... but... that's what decimals are for!! Fixed-point decimals are like specialized integers and they were designed for accounting and other applications where floating point rounding are unacceptable. The problem with floating points is not that the point is floating but that they are internally binary, so you have equivalence problems when you convert back and forth from decimal. But decimals are already in base 10, so you won't have this problem. Of course you shouldn't use float or double if rounding is a concern. However, integers can only express so much, which can be a problem in multi-currency systems. A good and compact decimal library is big.js (or derivates).
Anyway, thank you for this patch; there are many many cases where integers are good enough and better than floats.

**Comment by mbenedettini** [comment]
@guillep2 name your favorite three database systems which support fixed point decimals

**Comment by guillep2k** [comment]
@mbenedettini Oracle (Number), MongoDB 3.4+ (NumberDecimal), MSSQL (decimal), MySQL (decimal). Those are the databases I use every day.

**Comment by mbenedettini** [comment]
@guillep2k you'll end up with rounding errors anyway. Btw, in the first link I've posted there's an interesting paper by the Oracle folks https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by guillep2k** [comment]
@mbenedettini there are no rounding errors if you're not rounding. Our system is used in Customs in several countries; rest assured we've got our share of rounding errors before using decimals (decades ago). If you've got "333.556" and you need only two decimals, you will have to round up or truncate. But the same happens if you use integers and somehow end up with "33355.6" (like when calculating averages, distributing costs among accounts, etc.)

**Comment by guillep2k** [comment]
BTW, that Oracle paper is about binary floating point, not decimals.

**Pull request closed without merging**
