### PR TITLE
Flexibile Dependencies for Angular 12.2.x

### PR DESCRIPTION
**Pull request by mrlonis**
Allow other projects that use ng2-currency-mask to use higher version of Angular 12.2.x and rxjs 6.x.x

### CODE REVIEW

**Comment by gustavocipriani** [comment]
+1 to this @cesarrew 
Now that NodeJS 16 became the current LTS, a higher adoption of NPM 7 is to be expected,. Having the dependencies range correctly set up is going to become important as builds will start to break unless the users retort to options like using the "--legacy-peer-deps" flag.

**Comment by mrlonis** [comment]
I have already moved on to use a different currency mask... but I still care to see this one updated

**Comment by mrlonis** [comment]
tslib should also be updated to "^2.3.0" but I forgot to do it in this PR

**Comment by gustavocipriani** [comment]
> 
> 
> tslib should also be updated to "^2.3.0" but I forgot to do it in this PR

Right. Also, I'm thinking,... wouldn't be better to use carets instead of tildes in the Angular packages so it still works when a new minor (for example, angular 12.3.0) is released?

**Comment by gustavocipriani** [comment]
> 
> 
> I have already moved on to use a different currency mask... but I still care to see this one updated

Do you mind to share which one?

**Comment by mrlonis** [comment]
Honestly yes it would be better to use carets

**Comment by mrlonis** [comment]
I'm going to leave it up to the code maintainers to handle that decision though. Seems like they go inactive for months

**Comment by vladkasianenko** [comment]
> Do you mind to share which one?

Do you mind to share which one?

**Comment by mrlonis** [comment]
I found great success with this one: https://www.npmjs.com/package/ngx-currency

**Comment by cesarrew** [comment]
Thanks guys. Fixed this problem in version 13.0.0.

**Pull request closed without merging**
