### PR TITLE
Add ability to work from left to right and add decimal values only if…

### PR DESCRIPTION
**Pull request by thomaswdean**
According to some of the issues I read users need the ability to work left to right and/or to ignore the decimal places during entry. I believe that these changes provide not just that but also the ability to have the value selected on focus.

### CODE REVIEW

**Comment by hassanasad** [comment]
Can the admin/moderators please review this PR - Its a cool feature to have

**Comment by cesarrew** [comment]
@thomaswdean Hi. Thank you for this PR. I've merged it in my code and the mask didn't work, duplicating de prefix as example. I've tested it keeping the default values. It will be very helpful if you review and test this code.

**Comment by thomaswdean** [comment]
Ok. I realized what you were saying was what I had changed made the component only support the Left To Right entry so in my new PR I fixed that as well as making the direction a configurable option.

**Comment by pcbl** [comment]
Hey folks. Is this this feature going to be integrated to the component? I have a scenario where it will help a lot! Thanks again for the valuable work and keep up the great job!

**Pull request merged**
